# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-30 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_auto_20171227_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='limit',
            new_name='lim',
        ),
    ]
